# Generated by Django 6.0.2 on 2026-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwm_forcings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwmingestionlog',
            name='ingest_date',
            field=models.DateField(unique=True),
        ),
    ]
