# Generated by Django 6.0.2 on 2026-05-20 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_seed_forecast_percentile_computation'),
        ('streamflow', '0017_forecast_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('computation_type', models.CharField(choices=[('station_metadata', 'Station Metadata & Statistics'), ('flood_thresholds', 'Flood Thresholds (NOAA NWPS)'), ('percentile_backfill', 'Percentile Band Backfill')], max_length=30)),
                ('agency_filter', models.CharField(choices=[('ALL', 'All Agencies'), ('USGS', 'USGS'), ('EC', 'Environment Canada'), ('NOAA_RFC', 'NOAA RFC')], default='ALL', max_length=20)),
                ('schedule_type', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('custom', 'Custom Cron')], default='annual', max_length=20)),
                ('annual_run_month', models.IntegerField(default=10)),
                ('annual_run_day', models.IntegerField(default=1)),
                ('schedule_value', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'statistics_configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='computationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledcomputation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledcomputation',
            name='task_path',
            field=models.CharField(help_text='Dotted Celery task path, e.g. src.analytics.tasks.compute_flow_percentile_bands', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='FloodThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaa_lid', models.CharField(blank=True, max_length=50)),
                ('action_stage_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('action_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minor_stage_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minor_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moderate_stage_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('moderate_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('major_stage_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('major_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('record_stage_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('record_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(choices=[('noaa_api', 'NOAA API'), ('manual', 'Manual')], default='noaa_api', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flood_threshold', to='streamflow.station')),
            ],
            options={
                'db_table': 'flood_thresholds',
            },
        ),
        migrations.CreateModel(
            name='StationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_observation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('record_start_date', models.DateField(blank=True, null=True)),
                ('record_end_date', models.DateField(blank=True, null=True)),
                ('years_on_record', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_observation_count', models.IntegerField(blank=True, null=True)),
                ('record_completeness_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_annual_flow_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('q10_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('q25_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('q50_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('q75_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('q90_cfs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='streamflow.station')),
            ],
            options={
                'db_table': 'station_metadata',
            },
        ),
        migrations.CreateModel(
            name='StatisticsComputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stations_processed', models.IntegerField(blank=True, null=True)),
                ('records_computed', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analytics.statisticsconfiguration')),
            ],
            options={
                'db_table': 'statistics_computation_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['configuration', 'started_at'], name='idx_stat_log_config_started'), models.Index(fields=['status'], name='idx_stat_log_status')],
            },
        ),
        migrations.CreateModel(
            name='StatisticsConfigurationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='analytics.statisticsconfiguration')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamflow.station')),
            ],
            options={
                'db_table': 'statistics_configuration_stations',
                'unique_together': {('configuration', 'station')},
            },
        ),
    ]
