# Generated by Django 6.0.2 on 2026-05-20 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analytics_station_statistics'),
        ('streamflow', '0017_forecast_percentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsconfiguration',
            name='annual_run_day',
            field=models.IntegerField(default=1, help_text='Day of month for annual runs (1–31). Default: 1.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='statisticsconfiguration',
            name='annual_run_month',
            field=models.IntegerField(default=10, help_text='Month for annual runs (1–12). Default: 10 (October, water year start).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='statisticsconfiguration',
            name='schedule_value',
            field=models.CharField(blank=True, help_text="Cron expression (5 fields: min hr dom mon dow) — required when schedule_type is 'custom'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='statisticsconfigurationstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_configuration_stations', to='streamflow.station'),
        ),
    ]
