# Generated by Django 6.0.2 on 2026-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_add_validators_to_statistics_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsconfiguration',
            name='computation_type',
            field=models.CharField(choices=[('station_metadata', 'Station Metadata & Statistics'), ('flood_thresholds', 'Flood Thresholds (NOAA NWPS)'), ('daily_flow_percentiles', 'Observed Flow Percentiles (Daily)'), ('forecast_percentiles', 'Forecast Flow Percentiles (NOAA NWRFC)'), ('percentile_backfill', 'Percentile Band Historical Backfill')], max_length=30),
        ),
    ]
