# Generated by Django 4.2.7 on 2025-12-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataPullLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "data_pull_logs",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="DischargeObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("discharge", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("cfs", "Cubic Feet per Second"),
                            ("cms", "Cubic Meters per Second"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("realtime_15min", "Real-time 15 min"),
                            ("daily_mean", "Daily Mean"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quality_code",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Provisional"), ("A", "Approved")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "discharge_observations",
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("NOAA_RFC", "NOAA River Forecast Center")],
                        max_length=50,
                    ),
                ),
                ("run_date", models.DateTimeField(db_index=True)),
                (
                    "data",
                    models.JSONField(
                        help_text="Array of { date: string, value: number }"
                    ),
                ),
                (
                    "rmse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Accuracy metric",
                        max_digits=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "forecast_runs",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="MasterStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("station_name", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "state_code",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                (
                    "huc_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "altitude_ft",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "drainage_area_sqmi",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[("USGS", "USGS"), ("EC", "Environment Canada")],
                        default="USGS",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "master_stations",
                "ordering": ["station_number"],
            },
        ),
        migrations.CreateModel(
            name="PullConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("realtime_15min", "Real-time 15 min"),
                            ("daily_mean", "Daily Mean"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_strategy",
                    models.CharField(
                        choices=[("append", "Append"), ("overwrite", "Overwrite")],
                        max_length=20,
                    ),
                ),
                ("pull_start_date", models.DateTimeField()),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom Cron"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule_value",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '0 */6 * * *' for cron",
                        max_length=50,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pull_configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PullConfigurationStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_number", models.CharField(max_length=50)),
                ("station_name", models.TextField(blank=True)),
                ("huc_code", models.CharField(blank=True, max_length=20)),
                ("state", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "pull_configuration_stations",
            },
        ),
        migrations.CreateModel(
            name="PullStationProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_number", models.CharField(max_length=50)),
                (
                    "last_successful_pull_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pull_station_progress",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.TextField()),
                (
                    "agency",
                    models.CharField(
                        choices=[("USGS", "USGS"), ("EC", "Environment Canada")],
                        max_length=50,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "huc_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("basin", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "catchment_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="sq km",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "years_of_record",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("record_start_date", models.DateTimeField(blank=True, null=True)),
                ("record_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stations",
                "ordering": ["station_number"],
            },
        ),
        migrations.CreateModel(
            name="StationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_agency", models.CharField(max_length=50)),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("target_agency", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "station_mappings",
                "indexes": [
                    models.Index(
                        fields=["source_agency", "source_id"], name="idx_source_lookup"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stationmapping",
            constraint=models.UniqueConstraint(
                fields=("source_agency", "source_id", "target_agency"),
                name="unique_mapping_idx",
            ),
        ),
        migrations.AddField(
            model_name="pullstationprogress",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="streamflow.pullconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="pullconfigurationstation",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuration_stations",
                to="streamflow.pullconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="forecastrun",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast_runs",
                to="streamflow.station",
            ),
        ),
        migrations.AddField(
            model_name="dischargeobservation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discharge_observations",
                to="streamflow.station",
            ),
        ),
        migrations.AddField(
            model_name="datapulllog",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="streamflow.pullconfiguration",
            ),
        ),
        migrations.AddConstraint(
            model_name="pullstationprogress",
            constraint=models.UniqueConstraint(
                fields=("configuration", "station_number"), name="unique_progress_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecastrun",
            index=models.Index(
                fields=["station", "run_date"], name="idx_station_run_date"
            ),
        ),
        migrations.AddIndex(
            model_name="dischargeobservation",
            index=models.Index(
                fields=["station", "observed_at", "type"],
                name="idx_station_observed_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="dischargeobservation",
            constraint=models.UniqueConstraint(
                fields=("station", "observed_at", "type"), name="unique_observation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datapulllog",
            index=models.Index(
                fields=["configuration", "start_time"], name="idx_config_start_time"
            ),
        ),
    ]
