# Generated by Django 4.2.27 on 2026-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullconfiguration',
            name='data_source',
            field=models.CharField(choices=[('USGS', 'USGS NWIS'), ('EC', 'Environment Canada'), ('NOAA', 'NOAA National Water Model')], default='USGS', max_length=20),
        ),
    ]
