# Generated by Django 4.2.27 on 2026-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0002_add_data_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstation',
            name='noaa_lid',
            field=models.CharField(blank=True, db_index=True, help_text='NOAA Location ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='masterstation',
            name='rfc_code',
            field=models.CharField(blank=True, db_index=True, help_text='River Forecast Center code (e.g., NWRFC, CNRFC)', max_length=20),
        ),
        migrations.AlterField(
            model_name='masterstation',
            name='agency',
            field=models.CharField(choices=[('USGS', 'USGS'), ('EC', 'Environment Canada'), ('NOAA_RFC', 'NOAA River Forecast Center')], default='USGS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pullconfiguration',
            name='data_source',
            field=models.CharField(choices=[('USGS', 'USGS NWIS'), ('EC', 'Environment Canada'), ('NOAA', 'NOAA National Water Model'), ('NOAA_RFC', 'NOAA River Forecast Center')], default='USGS', max_length=20),
        ),
        migrations.AlterField(
            model_name='pullconfiguration',
            name='data_type',
            field=models.CharField(choices=[('realtime_15min', 'Real-time 15 min'), ('daily_mean', 'Daily Mean'), ('forecast', 'Forecast')], max_length=20),
        ),
        migrations.AlterField(
            model_name='station',
            name='agency',
            field=models.CharField(choices=[('USGS', 'USGS'), ('EC', 'Environment Canada'), ('NOAA_RFC', 'NOAA River Forecast Center')], max_length=50),
        ),
    ]
