# Generated by Django 4.2.27 on 2026-01-27 19:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0003_masterstation_noaa_lid_masterstation_rfc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Human-readable dataset name (e.g., 'RTMA', 'SMAP SPL4')", max_length=100, unique=True)),
                ('gee_collection_id', models.CharField(help_text="Google Earth Engine collection ID (e.g., 'NOAA/NWS/RTMA')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resolution_m', models.IntegerField(help_text='Native resolution in meters')),
                ('temporal_resolution', models.CharField(help_text="e.g., 'hourly', 'daily', '3-hourly'", max_length=50)),
                ('update_frequency', models.CharField(help_text='How often new data is available', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raster_datasets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RasterPullConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schedule_enabled', models.BooleanField(default=True)),
                ('schedule_cron', models.CharField(blank=True, help_text='Celery cron expression', max_length=100)),
                ('pull_frequency_hours', models.IntegerField(default=8, help_text='Hours between pulls')),
                ('lookback_days', models.IntegerField(default=7, help_text='Days of historical data to check')),
                ('max_age_hours', models.IntegerField(default=24, help_text="Maximum age of data to consider 'current'")),
                ('resampling_method', models.CharField(default='bilinear', help_text="e.g., 'nearest', 'bilinear', 'cubic'", max_length=50)),
                ('target_resolution_m', models.IntegerField(blank=True, help_text='Target resolution for resampling (null = native)', null=True)),
                ('apply_compression', models.BooleanField(default=True)),
                ('generate_thumbnails', models.BooleanField(default=True)),
                ('validate_on_pull', models.BooleanField(default=True)),
                ('calculate_statistics', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_pull', models.DateTimeField(blank=True, null=True)),
                ('last_pull_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_configs', to='streamflow.rasterdataset')),
            ],
            options={
                'db_table': 'raster_pull_configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpatialExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'HUC_17', 'Western_US'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Precise boundary polygon', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spatial_extents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RasterVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variable name (e.g., 'temperature', 'precipitation')", max_length=100)),
                ('gee_band_name', models.CharField(help_text="Band name in GEE (e.g., 'TMP', 'APCP')", max_length=100)),
                ('unit', models.CharField(help_text="Measurement unit (e.g., 'Kelvin', 'mm', 'm/s')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('min_valid_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_valid_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='streamflow.rasterdataset')),
            ],
            options={
                'db_table': 'raster_variables',
                'ordering': ['dataset', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RasterPullLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('layers_attempted', models.IntegerField(default=0)),
                ('layers_successful', models.IntegerField(default=0)),
                ('layers_failed', models.IntegerField(default=0)),
                ('layers_skipped', models.IntegerField(default=0, help_text='Already existed')),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, help_text='List of warning messages', null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pull_logs', to='streamflow.rasterpullconfiguration')),
            ],
            options={
                'db_table': 'raster_pull_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='rasterpullconfiguration',
            name='extents',
            field=models.ManyToManyField(related_name='pull_configs', to='streamflow.spatialextent'),
        ),
        migrations.AddField(
            model_name='rasterpullconfiguration',
            name='variables',
            field=models.ManyToManyField(related_name='pull_configs', to='streamflow.rastervariable'),
        ),
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Data timestamp (UTC)')),
                ('date', models.DateField(db_index=True, help_text='Date component for easier querying')),
                ('file_path', models.CharField(help_text='Relative path to raster file', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('format', models.CharField(default='GeoTIFF', max_length=20)),
                ('compression', models.CharField(default='LZW', max_length=20)),
                ('resolution_m', models.IntegerField(help_text='Actual resolution in meters')),
                ('width_pixels', models.IntegerField()),
                ('height_pixels', models.IntegerField()),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('mean_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('std_dev', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('no_data_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to thumbnail image', max_length=500)),
                ('checksum_md5', models.CharField(blank=True, help_text='File integrity checksum', max_length=32)),
                ('is_valid', models.BooleanField(default=True, help_text='Passed validation checks')),
                ('validation_errors', models.JSONField(blank=True, help_text='Validation error messages', null=True)),
                ('processing_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='streamflow.spatialextent')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='streamflow.rastervariable')),
            ],
            options={
                'db_table': 'raster_layers',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='rastervariable',
            constraint=models.UniqueConstraint(fields=('dataset', 'name'), name='unique_dataset_variable'),
        ),
        migrations.AddIndex(
            model_name='rasterpulllog',
            index=models.Index(fields=['-started_at'], name='idx_pull_log_started'),
        ),
        migrations.AddIndex(
            model_name='rasterpulllog',
            index=models.Index(fields=['status'], name='idx_pull_log_status'),
        ),
        migrations.AddIndex(
            model_name='rasterpulllog',
            index=models.Index(fields=['configuration', '-started_at'], name='idx_pull_log_config'),
        ),
        migrations.AddIndex(
            model_name='rasterlayer',
            index=models.Index(fields=['variable', 'extent', 'date'], name='idx_raster_var_ext_date'),
        ),
        migrations.AddIndex(
            model_name='rasterlayer',
            index=models.Index(fields=['variable', 'timestamp'], name='idx_raster_var_time'),
        ),
        migrations.AddIndex(
            model_name='rasterlayer',
            index=models.Index(fields=['is_valid'], name='idx_raster_valid'),
        ),
        migrations.AddConstraint(
            model_name='rasterlayer',
            constraint=models.UniqueConstraint(fields=('variable', 'extent', 'timestamp'), name='unique_raster_layer'),
        ),
    ]
