# Generated by Django 4.2.27 on 2026-01-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0005_update_dataset_for_earthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdataset',
            name='access_url_pattern',
            field=models.CharField(blank=True, help_text='URL pattern for direct access (NOMADS) or base URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rasterdataset',
            name='collection_id',
            field=models.CharField(help_text="Collection/dataset ID (GEE: 'NOAA/NWS/RTMA', EarthData: 'SPL4SMGP_008', NOMADS: 'rtma2p5')", max_length=255),
        ),
        migrations.AlterField(
            model_name='rasterdataset',
            name='daac',
            field=models.CharField(blank=True, help_text='NASA DAAC archive (e.g., NSIDC_CPRD, GES_DISC, LPDAAC_ECS) - EarthData only', max_length=50, null=True),
        ),
    ]
