# Generated by Django 4.2.27 on 2026-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0006_alter_rasterdataset_access_url_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullconfiguration',
            name='forecast_type',
            field=models.CharField(blank=True, choices=[('short', 'Short-range (3-7 days)'), ('medium', 'Medium-range (up to 10 days)'), ('long', 'Long-range (up to 30 days)')], default='short', help_text='Forecast duration (only applies to forecast data type)', max_length=20),
        ),
    ]
