# Generated by Django 4.2.27 on 2026-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0007_add_forecast_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterlayer',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Path to thumbnail image', max_length=500, null=True),
        ),
    ]
