# Generated by Django 4.2.27 on 2026-01-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0008_alter_rasterlayer_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='historical_data_populated_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Timestamp when complete historical data was populated'
            ),
        ),
        migrations.AddField(
            model_name='station',
            name='historical_record_count',
            field=models.IntegerField(
                default=0,
                help_text='Count of historical records populated'
            ),
        ),
    ]
