# Generated by Django on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0009_add_historical_tracking_to_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='forecast_type',
            field=models.CharField(
                choices=[
                    ('short', 'Short-range (3-7 days)'),
                    ('medium', 'Medium-range (up to 10 days)'),
                    ('long', 'Long-range (up to 30 days)')
                ],
                default='short',
                help_text='Forecast duration type',
                max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.UniqueConstraint(
                fields=['station', 'source', 'run_date', 'forecast_type'],
                name='unique_forecast_run'
            ),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(
                fields=['station', 'run_date', 'forecast_type'],
                name='idx_station_run_date_type'
            ),
        ),
    ]
