# Generated by Django 4.2.27 on 2026-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0010_add_forecast_type_to_forecast_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastrun',
            name='run_date',
            field=models.DateTimeField(db_index=True, help_text='When forecast was issued'),
        ),
    ]
