# Generated by Django 6.0.2 on 2026-05-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0016_split_p76_100_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPercentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True, help_text='Forecasted date')),
                ('source', models.CharField(help_text='Forecast source label, e.g. NWRFC', max_length=50)),
                ('forecast_run_date', models.DateTimeField(help_text='Issuance datetime of the ForecastRun used')),
                ('forecast_discharge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('percentile_rank', models.DecimalField(decimal_places=2, help_text="0–100; compared against station's full period-of-record daily_mean observations", max_digits=5)),
                ('band', models.CharField(choices=[('p0_4', 'Very Low (0–4th percentile)'), ('p5_10', 'Low (5th–10th percentile)'), ('p11_25', 'Below Normal (11th–25th percentile)'), ('p26_50', 'Normal (26th–50th percentile)'), ('p51_75', 'Above Normal (51st–75th percentile)'), ('p76_85', 'High (76th–85th percentile)'), ('p86_90', 'Very High (86th–90th percentile)'), ('p91_95', 'Extreme (91st–95th percentile)'), ('p96_98', 'Severe (96th–98th percentile)'), ('p99_100', 'Exceptional (>98th percentile)')], max_length=10)),
                ('historical_record_count', models.IntegerField(help_text='Total daily_mean records used in the percentile computation')),
                ('computed_at', models.DateTimeField(help_text='When this row was computed')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_percentiles', to='streamflow.station')),
            ],
            options={
                'db_table': 'forecast_percentiles',
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['station', 'target_date'], name='idx_fcst_pct_station_date'), models.Index(fields=['source', 'target_date'], name='idx_fcst_pct_source_date')],
                'constraints': [models.UniqueConstraint(fields=('station', 'target_date', 'source'), name='unique_forecast_percentile')],
            },
        ),
    ]
