# Generated by Django 6.0.2 on 2026-05-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0017_forecast_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasinForcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('prcp_mm_day', models.FloatField(help_text='Precipitation mm/day')),
                ('tmax_c', models.FloatField(help_text='Maximum air temperature °C')),
                ('tmin_c', models.FloatField(help_text='Minimum air temperature °C')),
                ('srad_w_m2', models.FloatField(help_text='Downward shortwave radiation W/m²')),
                ('vp_pa', models.FloatField(help_text='Vapor pressure Pa')),
                ('dayl_s', models.FloatField(help_text='Day length seconds/day')),
                ('source', models.CharField(choices=[('nwm', 'NWM Medium-Range'), ('daymet', 'Daymet CAMELS')], default='nwm', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin_forcings', to='streamflow.station')),
            ],
            options={
                'db_table': 'basin_forcings',
                'ordering': ['station', 'date'],
                'unique_together': {('station', 'date', 'source')},
            },
        ),
    ]
