# Generated by Django 6.0.2 on 2026-05-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0018_add_basin_forcing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basinforcing',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='basinforcing',
            constraint=models.UniqueConstraint(fields=('station', 'date', 'source'), name='unique_basin_forcing'),
        ),
    ]
