# Generated by Django 6.0.2 on 2026-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0019_update_basin_forcing_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdataset',
            name='data_source',
            field=models.CharField(choices=[('earthdata', 'NASA EarthData'), ('nomads', 'NOAA NOMADS'), ('nwm_s3', 'NOAA NWM S3'), ('gee', 'Google Earth Engine (deprecated)')], default='earthdata', help_text='Data source provider', max_length=20),
        ),
    ]
