# Generated by Django 6.0.2 on 2026-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0020_add_nwm_s3_data_source_choice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forecastrun',
            name='unique_forecast_run',
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='is_forecast',
            field=models.BooleanField(default=True, help_text='True = forecast rows; False = observed rows scraped from same page'),
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='source',
            field=models.CharField(choices=[('NOAA_RFC', 'NOAA River Forecast Center'), ('nwrfc_web', 'NWRFC Website')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pullconfiguration',
            name='data_source',
            field=models.CharField(choices=[('USGS', 'USGS NWIS'), ('EC', 'Environment Canada'), ('NOAA', 'NOAA National Water Model'), ('NOAA_RFC', 'NOAA River Forecast Center'), ('nwrfc_web', 'NWRFC Website (scraper)')], default='USGS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.UniqueConstraint(fields=('station', 'source', 'run_date', 'forecast_type', 'is_forecast'), name='unique_forecast_run'),
        ),
    ]
