# Generated by Django 6.0.2 on 2026-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0021_forecastrun_nwrfc_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapulllog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20),
        ),
    ]
