# Generated by Django 6.0.2 on 2026-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflow', '0022_datapulllog_partial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullconfiguration',
            name='skip_inactive_stations',
            field=models.BooleanField(default=False, help_text='Only pull stations whose Station record is marked active. Skips discontinued gauges instead of requesting them every run. Leave off unless is_active is actually maintained for this data source — NOAA_RFC stations are all flagged inactive despite reporting, so enabling this would empty a forecast pull.'),
        ),
    ]
